---
new_page_extension: md
auto_deploy: true
admin_path: "/public/admin"
webhook_url: 
sections:
- type: document
  path: _content/index.md
  label: Home
- type: document
  path: _content/who-we-are/index.md
  label: Who We Are
- type: document
  path: _content/what-we-do/index.md
  label: What We Do
- type: directory
  path: _content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: _content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{**/index.*,{updates,services,who-we-are,what-we-do}/**/*}"
  new_doc_ext: md
  templates:
  - pages
- type: directory
  path: _content/updates
  label: Posts
  create: all
  match: "**/*"
  exclude: index.*
  new_doc_ext: md
  templates:
  - page-post
- type: directory
  path: _content/who-we-are
  label: Profiles
  create: documents
  match: "**/*"
  exclude: index.*
  templates:
  - profile
- type: document
  path: _data/testimonials.json
  label: Testimonials
- type: heading
  label: Config
- type: document
  path: data/formEmbedCodes.yaml
  label: Embed Codes
- type: document
  path: data/information.yaml
  label: Site Information
  templates:
  - site-information
- type: document
  path: _data/site-data.json
  label: Site Config
upload_dir: ''
public_path: https://res.cloudinary.com/navalign-wealth-partners/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.52
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
