---
label: Config
hide_body: true
fields:
- type: file
  name: header_logo
  label: Header Logo
- type: file
  name: footer_logo
  label: Footer Logo
- type: include
  name: social_accounts
  label: Social Accounts
  template: social-accounts
- type: include
  template: addresses
  label: Addresses
  name: addresses
- type: textarea
  name: site_disclaimer
  label: Site Disclaimer
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: file
  name: seo_logo
  label: SEO Logo
  description: 'This has to be a .png file. '
- type: text
  name: phone
  label: Phone
  description: Just the numbers. 2135551212
